### ISSUE TITLE
Incorrect Data

### ISSUE THREAD

**Issue by lyzerglick** [PokeDevs/pokedex.py#3]
The Pokemon "Gastrodon" in reality has two types, Water and Ground, but when checked in pokedex.py via 

`from pokedex import pokedex as pd`
`dex = pd.Pokedex(version='v1', user_agent='ExampleApp (https://example.com, v2.0.1)')`
`print(dex.get_pokemon_by_name('Gastrodon')[0]["types"])`

it returns only "Water" type. This is not an issue with other pokemon I have been able to check.

**Comment by iamtraction** [comment]
Same goes for 422. It's a bug in the API data itself. I'll fix it ASAP and will close this issue once done.
